ALTER TABLE jobs ADD COLUMN IF NOT EXISTS work_mode VARCHAR(20) DEFAULT 'on_site';
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS salary_currency VARCHAR(3) DEFAULT 'INR';
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS salary_period VARCHAR(20) DEFAULT 'annual';
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS visible_to_vendors BOOLEAN DEFAULT TRUE;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS visible_to_students BOOLEAN DEFAULT TRUE;
